spring.application.name=Aula

# Forma de update das entidades
# Podemos usar tambem o create-drop, para toda vez que rodar, ele cria a database e quando finaliza ele exclui, utilizado em ambientes de desenvolvimento
spring.jpa.hibernate.ddl-auto=update

# URL de conex�o e comando de cria��o
spring.datasource.url=jdbc:mysql://localhost:3306/CRUD?createDatabaseIfNotExist=true

# Usu�rio
spring.datasource.username=root

# Senha
spring.datasource.password=laboratorio