spring.application.name=Aula

# Forma de update das entidades
# Podemos usar tambem o create-drop, para toda vez que rodar, ele cria a database e quando finaliza ele exclui, utilizado em ambientes de desenvolvimento
spring.jpa.hibernate.ddl-auto=update

# URL de conexão e comando de criação
spring.datasource.url=jdbc:mysql://localhost:3306/CRUD?createDatabaseIfNotExist=true

# Usuário
spring.datasource.username=root

# Senha
spring.datasource.password=laboratorio